import fs from 'fs';
import path from 'path';
import { loadConfig } from './config.js';
import logger from './logger.js';
import { launchBrowser, launchSignupBrowser, closeSignupBrowser, closeBrowser } from './browser.js';
import { authorizeGmail } from './gmail.js';
import { performSignup, TooManyAttemptsError } from './signup.js';
import { handlePaywall } from './paywall.js';
import { handleVerification } from './verification.js';
import { handleOnboarding } from './onboarding.js';
import { saveAccountData } from './storage.js';
import { performLogout } from './logout.js';
import { getDDGEmail, DdgBlockedError } from './ddg-provider.js';
import { ProfileManager } from './profile-manager.js';
import { randomDelay } from './anti-detection.js';

const SIGNUP_URL = 'https://transcriptapi.com/signup';

/**
 * Save error diagnostic data (screenshot + HTML) for debugging
 */
async function saveErrorDiagnostics(page, errorsDir, accountNum, stepName, error) {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const prefix = `${timestamp}_account${accountNum}_${stepName}`;

  try {
    fs.mkdirSync(errorsDir, { recursive: true });
    const screenshotPath = path.join(errorsDir, `${prefix}.png`);
    await page.screenshot({ path: screenshotPath, fullPage: true });
    logger.debug(`Error screenshot saved: ${screenshotPath}`);
  } catch (err) {
    logger.warn(`Could not save screenshot: ${err.message}`);
  }

  try {
    const htmlPath = path.join(errorsDir, `${prefix}.html`);
    const html = await page.content();
    fs.writeFileSync(htmlPath, html, 'utf-8');
    logger.debug(`Error HTML saved: ${htmlPath}`);
  } catch (err) {
    logger.warn(`Could not save HTML: ${err.message}`);
  }

  try {
    const logPath = path.join(errorsDir, `${prefix}.log`);
    fs.writeFileSync(logPath, [
      `Account: #${accountNum}`,
      `Step: ${stepName}`,
      `Time: ${new Date().toISOString()}`,
      `URL: ${page.url()}`,
      `Error: ${error.message}`,
      `Stack: ${error.stack}`,
    ].join('\n'), 'utf-8');
  } catch { /* ignore */ }
}

/**
 * Execute one complete account creation cycle on the SIGNUP browser.
 * The email has already been generated by the DDG browser and is passed in.
 *
 * @returns {'success'|'fail'|'rate_limited'}
 */
async function createOneAccount(signupPage, gmailAuth, config, email, accountNum) {
  logger.newCycle(accountNum);

  let currentStep = 'signup';

  try {
    // Steps 1–6: Signup (email is pre-provided, just typed into the field)
    currentStep = 'signup';
    const { password, name } = await performSignup(signupPage, config, email);

    // Step 7: Paywall
    currentStep = 'paywall';
    await handlePaywall(signupPage, config);

    // Steps 8–10: Email verification
    currentStep = 'verification';
    await handleVerification(signupPage, email, gmailAuth, config);

    // Step 11: Dashboard API key
    currentStep = 'onboarding';
    const apiKey = await handleOnboarding(signupPage, config);

    // Step 12: Save data
    currentStep = 'save';
    await saveAccountData({ email, password, apiKey, createdAt: new Date().toISOString() }, config);

    // Step 13: Logout
    currentStep = 'logout';
    await performLogout(signupPage, config);

    logger.separator();
    logger.success(`Account #${accountNum} created successfully!`);
    logger.info(`  Email:   ${email}`);
    logger.info(`  API Key: ${apiKey.substring(0, 8)}...`);
    logger.separator();

    return 'success';

  } catch (error) {
    // ── Profile rate-limit: bubble up so caller can rotate profile ──────────
    if (error instanceof TooManyAttemptsError) {
      logger.warn(`Account #${accountNum}: profile rate-limited — will rotate profile`);
      return 'rate_limited';
    }

    logger.error(`Account #${accountNum} failed at step "${currentStep}": ${error.message}`);

    try {
      await saveErrorDiagnostics(signupPage, config.errorsDir, accountNum, currentStep, error);
    } catch { /* ignore */ }

    // Recovery: navigate back to signup
    try {
      logger.info('Attempting recovery — navigating to signup page...');
      await signupPage.goto(SIGNUP_URL, { waitUntil: 'domcontentloaded', timeout: 25000 });
      await randomDelay(2000, 3000);
      logger.info('Recovery successful');
    } catch (err2) {
      logger.error(`Recovery failed: ${err2.message}`);
    }

    return 'fail';
  }
}

/**
 * Main entry point
 */
async function main() {
  console.log(`
  ╔══════════════════════════════════════════════════╗
  ║      TranscriptAPI Account Automation Bot        ║
  ║                   v2.0.0 (Multi-Profile)         ║
  ╚══════════════════════════════════════════════════╝
  `);

  const config = loadConfig();

  // Authorize Gmail API
  logger.info('Initializing Gmail API...');
  const gmailAuth = await authorizeGmail(config);

  // ── Launch DDG browser (main Chrome profile with extension) ───────────────
  logger.info('Launching main DDG browser...');
  const { browser: ddgBrowser, context: ddgContext, page: ddgPage, chromeProcess: ddgProcess } = await launchBrowser(config);

  // Warm up the DDG extension (8s)
  logger.info('Warming up DDG browser extensions (8s)...');
  try {
    await ddgPage.goto(SIGNUP_URL, { waitUntil: 'domcontentloaded', timeout: 20000 });
    await randomDelay(8000, 10000);
    logger.info('DDG browser warmed up');
    // Close the initial page used for warmup to avoid leaks or persistence
    await ddgPage.close().catch(() => {});
  } catch {
    logger.warn('DDG warmup navigation failed — continuing anyway');
  }

  // ── Launch signup browser (fresh profile, no extensions) ─────────────────
  const profileManager = new ProfileManager(config);
  let signupBrowserState = await launchSignupBrowser(
    profileManager.getCurrentProfilePath(), config
  );
  let { browser: signupBrowser, page: signupPage } = signupBrowserState;

  const maxAccounts = config.maxAccounts;
  let accountNum = 0;
  let successCount = 0;
  let failCount = 0;
  let profileNum = 0;   // for display

  try {
    while (maxAccounts === 0 || accountNum < maxAccounts) {
      accountNum++;

      // ── Get DDG email from main browser ─────────────────────────────────
      let email;
      try {
        email = await getDDGEmail(ddgContext, config);
      } catch (ddgErr) {
        if (ddgErr instanceof DdgBlockedError) {
          logger.separator();
          logger.error(`[FATAL] DUCKDUCKGO IS BLOCKED / STUCK`);
          logger.error(`The bot detected that DuckDuckGo keeps returning the same email: "${ddgErr.email}"`);
          logger.error(`Please do the following to recover:`);
          logger.error(`1. Open the main Chrome profile manually.`);
          logger.error(`2. Go to the DDG extension or https://duckduckgo.com/email/ to ensure it generates new addresses.`);
          logger.error(`3. Run a manual generation to test, or log out and log back in.`);
          logger.error(`4. Once recovered, restart this bot script.`);
          logger.separator();
          process.exit(1);
        }
        logger.error(`DDG email generation failed: ${ddgErr.message}`);
        logger.info('Retrying DDG email in 5s...');
        await randomDelay(5000, 7000);
        accountNum--;  // don't count this attempt
        continue;
      }

      // ── Do the signup on the fresh-profile browser ───────────────────────
      const result = await createOneAccount(signupPage, gmailAuth, config, email, accountNum);

      if (result === 'success') {
        successCount++;
      } else if (result === 'rate_limited') {
        // ── Rotate to a new Chrome profile ───────────────────────────────
        logger.warn('🔄 Rotating signup profile due to rate limit...');
        await closeSignupBrowser(signupBrowser, config);

        const newProfilePath = profileManager.switchToNextProfile();
        profileNum++;
        logger.info(`Launching signup browser with profile #${profileNum}: ${newProfilePath}`);

        signupBrowserState = await launchSignupBrowser(newProfilePath, config);
        signupBrowser = signupBrowserState.browser;
        signupPage    = signupBrowserState.page;

        // Retry the same account number with the new profile
        accountNum--;
        logger.info('Profile rotated — retrying account with fresh profile...');
        await randomDelay(3000, 5000);
        continue;

      } else {
        failCount++;
      }

      logger.info(`Stats: ${successCount} successful, ${failCount} failed, ${accountNum} total`);

      if (maxAccounts > 0 && accountNum >= maxAccounts) {
        logger.info(`Reached max account limit (${maxAccounts}). Stopping.`);
        break;
      }

      const delay = config.delayBetweenAccounts;
      logger.info(`Waiting ${delay / 1000}s before next account...`);
      await randomDelay(delay, delay + 2000);
    }

  } catch (fatalError) {
    logger.error(`Fatal error: ${fatalError.message}`);
    logger.error(fatalError.stack);
  } finally {
    logger.separator();
    logger.info('=== Final Report ===');
    logger.info(`Total attempts: ${accountNum}`);
    logger.success(`Successful: ${successCount}`);
    if (failCount > 0) logger.error(`Failed: ${failCount}`);
    logger.info(`Profiles used: ${profileNum + 1}`);
    logger.separator();

    await closeSignupBrowser(signupBrowser, config).catch(() => {});
    await closeBrowser(ddgBrowser, ddgProcess);
    logger.info('Bot shutdown complete');
  }
}

// Run
main().catch(err => {
  logger.error(`Unhandled error: ${err.message}`);
  logger.error(err.stack);
  process.exit(1);
});
